### ISSUE TITLE
fix docker files and containers naming according to the convention

### ISSUE THREAD

**Issue by antonkulaga** [eliza-m/CrossSpeciesWorkflow#2]
The common convention about docker files naming are:
* having Dockerfile inside the folder (so isoglyp/Dockerfile and NOT isoglyp/isoglyp.dockerfile)
* having versions as tags and not as docker containers name (so netcglyc:1.0c and NOT netcglyc-1.0c)
* even if you build the containers locally, please tag them according to the docker registry where you publish them. For instance, if 
I build locally species_proteins and you know that you will publish it as quay.io/comp-bio-aging/species_proteins:latest you can tag it that way.

Because the namings of containers are nonstandard in your repository quay.io does not recognize docker files inside the repository (with exception of my own repository docker pull quay.io/comp-bio-aging/species_proteins for which I wrote a PullRequest)

**Comment by eliza-m** [comment]
Thanks ! They were changed to the standard 'Dockerfile' naming !
