### ISSUE TITLE
Writing CWL script for the main workflow

### ISSUE THREAD

**Issue by antonkulaga** [eliza-m/CrossSpeciesWorkflow#4]
Right now you have CWL for each of the tools, time to start writing CWL for the main workflow where you give an list of uniprot protein ids and it runs CWL scatter workflow and applied the tools for them and writes their results to specified folder

**Comment by eliza-m** [comment]
A CWL main & several sub workflows scripts are now available, although they will be further updated, refined and extended. I will mark this issue closed for now.
